(cl:defpackage rsi_lauv_ntnu-srv
  (:use )
  (:export
   "TESTSRVRSILAUV"
   "<TESTSRVRSILAUV-REQUEST>"
   "TESTSRVRSILAUV-REQUEST"
   "<TESTSRVRSILAUV-RESPONSE>"
   "TESTSRVRSILAUV-RESPONSE"
   "TESTSTATIONKEEPING"
   "<TESTSTATIONKEEPING-REQUEST>"
   "TESTSTATIONKEEPING-REQUEST"
   "<TESTSTATIONKEEPING-RESPONSE>"
   "TESTSTATIONKEEPING-RESPONSE"
  ))

