// Generated by gencpp from file g2s_interface/abort_Action.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_ABORT_ACTION_H
#define G2S_INTERFACE_MESSAGE_ABORT_ACTION_H

#include <ros/service_traits.h>


#include <g2s_interface/abort_ActionRequest.h>
#include <g2s_interface/abort_ActionResponse.h>


namespace g2s_interface
{

struct abort_Action
{

typedef abort_ActionRequest Request;
typedef abort_ActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct abort_Action
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::abort_Action > {
  static const char* value()
  {
    return "f353964018c9935fe8bd25629792d894";
  }

  static const char* value(const ::g2s_interface::abort_Action&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::abort_Action > {
  static const char* value()
  {
    return "g2s_interface/abort_Action";
  }

  static const char* value(const ::g2s_interface::abort_Action&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::abort_ActionRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::abort_Action > 
template<>
struct MD5Sum< ::g2s_interface::abort_ActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::abort_Action >::value();
  }
  static const char* value(const ::g2s_interface::abort_ActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::abort_ActionRequest> should match 
// service_traits::DataType< ::g2s_interface::abort_Action > 
template<>
struct DataType< ::g2s_interface::abort_ActionRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::abort_Action >::value();
  }
  static const char* value(const ::g2s_interface::abort_ActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::abort_ActionResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::abort_Action > 
template<>
struct MD5Sum< ::g2s_interface::abort_ActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::abort_Action >::value();
  }
  static const char* value(const ::g2s_interface::abort_ActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::abort_ActionResponse> should match 
// service_traits::DataType< ::g2s_interface::abort_Action > 
template<>
struct DataType< ::g2s_interface::abort_ActionResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::abort_Action >::value();
  }
  static const char* value(const ::g2s_interface::abort_ActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_ABORT_ACTION_H
