// Generated by gencpp from file g2s_interface/activateLASER.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_ACTIVATELASER_H
#define G2S_INTERFACE_MESSAGE_ACTIVATELASER_H

#include <ros/service_traits.h>


#include <g2s_interface/activateLASERRequest.h>
#include <g2s_interface/activateLASERResponse.h>


namespace g2s_interface
{

struct activateLASER
{

typedef activateLASERRequest Request;
typedef activateLASERResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct activateLASER
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::activateLASER > {
  static const char* value()
  {
    return "71a43a7268e3d956360fcea457136a33";
  }

  static const char* value(const ::g2s_interface::activateLASER&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::activateLASER > {
  static const char* value()
  {
    return "g2s_interface/activateLASER";
  }

  static const char* value(const ::g2s_interface::activateLASER&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::activateLASERRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::activateLASER > 
template<>
struct MD5Sum< ::g2s_interface::activateLASERRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::activateLASER >::value();
  }
  static const char* value(const ::g2s_interface::activateLASERRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::activateLASERRequest> should match 
// service_traits::DataType< ::g2s_interface::activateLASER > 
template<>
struct DataType< ::g2s_interface::activateLASERRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::activateLASER >::value();
  }
  static const char* value(const ::g2s_interface::activateLASERRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::activateLASERResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::activateLASER > 
template<>
struct MD5Sum< ::g2s_interface::activateLASERResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::activateLASER >::value();
  }
  static const char* value(const ::g2s_interface::activateLASERResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::activateLASERResponse> should match 
// service_traits::DataType< ::g2s_interface::activateLASER > 
template<>
struct DataType< ::g2s_interface::activateLASERResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::activateLASER >::value();
  }
  static const char* value(const ::g2s_interface::activateLASERResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_ACTIVATELASER_H
