// Generated by gencpp from file g2s_interface/activateACOUSTIC.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_ACTIVATEACOUSTIC_H
#define G2S_INTERFACE_MESSAGE_ACTIVATEACOUSTIC_H

#include <ros/service_traits.h>


#include <g2s_interface/activateACOUSTICRequest.h>
#include <g2s_interface/activateACOUSTICResponse.h>


namespace g2s_interface
{

struct activateACOUSTIC
{

typedef activateACOUSTICRequest Request;
typedef activateACOUSTICResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct activateACOUSTIC
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::activateACOUSTIC > {
  static const char* value()
  {
    return "71a43a7268e3d956360fcea457136a33";
  }

  static const char* value(const ::g2s_interface::activateACOUSTIC&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::activateACOUSTIC > {
  static const char* value()
  {
    return "g2s_interface/activateACOUSTIC";
  }

  static const char* value(const ::g2s_interface::activateACOUSTIC&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::activateACOUSTICRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::activateACOUSTIC > 
template<>
struct MD5Sum< ::g2s_interface::activateACOUSTICRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::activateACOUSTIC >::value();
  }
  static const char* value(const ::g2s_interface::activateACOUSTICRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::activateACOUSTICRequest> should match 
// service_traits::DataType< ::g2s_interface::activateACOUSTIC > 
template<>
struct DataType< ::g2s_interface::activateACOUSTICRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::activateACOUSTIC >::value();
  }
  static const char* value(const ::g2s_interface::activateACOUSTICRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::activateACOUSTICResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::activateACOUSTIC > 
template<>
struct MD5Sum< ::g2s_interface::activateACOUSTICResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::activateACOUSTIC >::value();
  }
  static const char* value(const ::g2s_interface::activateACOUSTICResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::activateACOUSTICResponse> should match 
// service_traits::DataType< ::g2s_interface::activateACOUSTIC > 
template<>
struct DataType< ::g2s_interface::activateACOUSTICResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::activateACOUSTIC >::value();
  }
  static const char* value(const ::g2s_interface::activateACOUSTICResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_ACTIVATEACOUSTIC_H
