// Generated by gencpp from file g2s_interface/activateUSBL.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_ACTIVATEUSBL_H
#define G2S_INTERFACE_MESSAGE_ACTIVATEUSBL_H

#include <ros/service_traits.h>


#include <g2s_interface/activateUSBLRequest.h>
#include <g2s_interface/activateUSBLResponse.h>


namespace g2s_interface
{

struct activateUSBL
{

typedef activateUSBLRequest Request;
typedef activateUSBLResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct activateUSBL
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::activateUSBL > {
  static const char* value()
  {
    return "71a43a7268e3d956360fcea457136a33";
  }

  static const char* value(const ::g2s_interface::activateUSBL&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::activateUSBL > {
  static const char* value()
  {
    return "g2s_interface/activateUSBL";
  }

  static const char* value(const ::g2s_interface::activateUSBL&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::activateUSBLRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::activateUSBL > 
template<>
struct MD5Sum< ::g2s_interface::activateUSBLRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::activateUSBL >::value();
  }
  static const char* value(const ::g2s_interface::activateUSBLRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::activateUSBLRequest> should match 
// service_traits::DataType< ::g2s_interface::activateUSBL > 
template<>
struct DataType< ::g2s_interface::activateUSBLRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::activateUSBL >::value();
  }
  static const char* value(const ::g2s_interface::activateUSBLRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::activateUSBLResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::activateUSBL > 
template<>
struct MD5Sum< ::g2s_interface::activateUSBLResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::activateUSBL >::value();
  }
  static const char* value(const ::g2s_interface::activateUSBLResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::activateUSBLResponse> should match 
// service_traits::DataType< ::g2s_interface::activateUSBL > 
template<>
struct DataType< ::g2s_interface::activateUSBLResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::activateUSBL >::value();
  }
  static const char* value(const ::g2s_interface::activateUSBLResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_ACTIVATEUSBL_H
