// Generated by gencpp from file g2s_interface/deactivateEqpt.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_DEACTIVATEEQPT_H
#define G2S_INTERFACE_MESSAGE_DEACTIVATEEQPT_H

#include <ros/service_traits.h>


#include <g2s_interface/deactivateEqptRequest.h>
#include <g2s_interface/deactivateEqptResponse.h>


namespace g2s_interface
{

struct deactivateEqpt
{

typedef deactivateEqptRequest Request;
typedef deactivateEqptResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct deactivateEqpt
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::deactivateEqpt > {
  static const char* value()
  {
    return "b5355e42a58b4a0869f6eec588b87b38";
  }

  static const char* value(const ::g2s_interface::deactivateEqpt&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::deactivateEqpt > {
  static const char* value()
  {
    return "g2s_interface/deactivateEqpt";
  }

  static const char* value(const ::g2s_interface::deactivateEqpt&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::deactivateEqptRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::deactivateEqpt > 
template<>
struct MD5Sum< ::g2s_interface::deactivateEqptRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::deactivateEqpt >::value();
  }
  static const char* value(const ::g2s_interface::deactivateEqptRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::deactivateEqptRequest> should match 
// service_traits::DataType< ::g2s_interface::deactivateEqpt > 
template<>
struct DataType< ::g2s_interface::deactivateEqptRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::deactivateEqpt >::value();
  }
  static const char* value(const ::g2s_interface::deactivateEqptRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::deactivateEqptResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::deactivateEqpt > 
template<>
struct MD5Sum< ::g2s_interface::deactivateEqptResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::deactivateEqpt >::value();
  }
  static const char* value(const ::g2s_interface::deactivateEqptResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::deactivateEqptResponse> should match 
// service_traits::DataType< ::g2s_interface::deactivateEqpt > 
template<>
struct DataType< ::g2s_interface::deactivateEqptResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::deactivateEqpt >::value();
  }
  static const char* value(const ::g2s_interface::deactivateEqptResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_DEACTIVATEEQPT_H
