// Generated by gencpp from file g2s_interface/robotSituation.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_ROBOTSITUATION_H
#define G2S_INTERFACE_MESSAGE_ROBOTSITUATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace g2s_interface
{
template <class ContainerAllocator>
struct robotSituation_
{
  typedef robotSituation_<ContainerAllocator> Type;

  robotSituation_()
    : header()
    , robotPose()
    , robotSpeed(0.0)
    , robotAltitude(0.0)  {
    }
  robotSituation_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robotPose(_alloc)
    , robotSpeed(0.0)
    , robotAltitude(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _robotPose_type;
  _robotPose_type robotPose;

   typedef float _robotSpeed_type;
  _robotSpeed_type robotSpeed;

   typedef float _robotAltitude_type;
  _robotAltitude_type robotAltitude;




  typedef boost::shared_ptr< ::g2s_interface::robotSituation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::g2s_interface::robotSituation_<ContainerAllocator> const> ConstPtr;

}; // struct robotSituation_

typedef ::g2s_interface::robotSituation_<std::allocator<void> > robotSituation;

typedef boost::shared_ptr< ::g2s_interface::robotSituation > robotSituationPtr;
typedef boost::shared_ptr< ::g2s_interface::robotSituation const> robotSituationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::g2s_interface::robotSituation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::g2s_interface::robotSituation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace g2s_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'g2s_interface': ['/home/uvlab/swarms/catkin_ws/src/rgi_rsi/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::g2s_interface::robotSituation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::g2s_interface::robotSituation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::g2s_interface::robotSituation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::g2s_interface::robotSituation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::g2s_interface::robotSituation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::g2s_interface::robotSituation_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::g2s_interface::robotSituation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0fb0af8bac49959593454f2fe2e8d25";
  }

  static const char* value(const ::g2s_interface::robotSituation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0fb0af8bac49959ULL;
  static const uint64_t static_value2 = 0x593454f2fe2e8d25ULL;
};

template<class ContainerAllocator>
struct DataType< ::g2s_interface::robotSituation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "g2s_interface/robotSituation";
  }

  static const char* value(const ::g2s_interface::robotSituation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::g2s_interface::robotSituation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
geometry_msgs/Pose robotPose\n\
float32 robotSpeed\n\
float32 robotAltitude\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::g2s_interface::robotSituation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::g2s_interface::robotSituation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robotPose);
      stream.next(m.robotSpeed);
      stream.next(m.robotAltitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct robotSituation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::g2s_interface::robotSituation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::g2s_interface::robotSituation_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robotPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.robotPose);
    s << indent << "robotSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.robotSpeed);
    s << indent << "robotAltitude: ";
    Printer<float>::stream(s, indent + "  ", v.robotAltitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_ROBOTSITUATION_H
