// Generated by gencpp from file g2s_interface/runASCEND_GPS.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_RUNASCEND_GPS_H
#define G2S_INTERFACE_MESSAGE_RUNASCEND_GPS_H

#include <ros/service_traits.h>


#include <g2s_interface/runASCEND_GPSRequest.h>
#include <g2s_interface/runASCEND_GPSResponse.h>


namespace g2s_interface
{

struct runASCEND_GPS
{

typedef runASCEND_GPSRequest Request;
typedef runASCEND_GPSResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct runASCEND_GPS
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::runASCEND_GPS > {
  static const char* value()
  {
    return "f138974fb822f7619b09d9993cb36c12";
  }

  static const char* value(const ::g2s_interface::runASCEND_GPS&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::runASCEND_GPS > {
  static const char* value()
  {
    return "g2s_interface/runASCEND_GPS";
  }

  static const char* value(const ::g2s_interface::runASCEND_GPS&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::runASCEND_GPSRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::runASCEND_GPS > 
template<>
struct MD5Sum< ::g2s_interface::runASCEND_GPSRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runASCEND_GPS >::value();
  }
  static const char* value(const ::g2s_interface::runASCEND_GPSRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runASCEND_GPSRequest> should match 
// service_traits::DataType< ::g2s_interface::runASCEND_GPS > 
template<>
struct DataType< ::g2s_interface::runASCEND_GPSRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runASCEND_GPS >::value();
  }
  static const char* value(const ::g2s_interface::runASCEND_GPSRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::runASCEND_GPSResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::runASCEND_GPS > 
template<>
struct MD5Sum< ::g2s_interface::runASCEND_GPSResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runASCEND_GPS >::value();
  }
  static const char* value(const ::g2s_interface::runASCEND_GPSResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runASCEND_GPSResponse> should match 
// service_traits::DataType< ::g2s_interface::runASCEND_GPS > 
template<>
struct DataType< ::g2s_interface::runASCEND_GPSResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runASCEND_GPS >::value();
  }
  static const char* value(const ::g2s_interface::runASCEND_GPSResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_RUNASCEND_GPS_H
