// Generated by gencpp from file g2s_interface/runGOTO_WAYPOINT.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_RUNGOTO_WAYPOINT_H
#define G2S_INTERFACE_MESSAGE_RUNGOTO_WAYPOINT_H

#include <ros/service_traits.h>


#include <g2s_interface/runGOTO_WAYPOINTRequest.h>
#include <g2s_interface/runGOTO_WAYPOINTResponse.h>


namespace g2s_interface
{

struct runGOTO_WAYPOINT
{

typedef runGOTO_WAYPOINTRequest Request;
typedef runGOTO_WAYPOINTResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct runGOTO_WAYPOINT
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::runGOTO_WAYPOINT > {
  static const char* value()
  {
    return "f138974fb822f7619b09d9993cb36c12";
  }

  static const char* value(const ::g2s_interface::runGOTO_WAYPOINT&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::runGOTO_WAYPOINT > {
  static const char* value()
  {
    return "g2s_interface/runGOTO_WAYPOINT";
  }

  static const char* value(const ::g2s_interface::runGOTO_WAYPOINT&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::runGOTO_WAYPOINTRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::runGOTO_WAYPOINT > 
template<>
struct MD5Sum< ::g2s_interface::runGOTO_WAYPOINTRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runGOTO_WAYPOINT >::value();
  }
  static const char* value(const ::g2s_interface::runGOTO_WAYPOINTRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runGOTO_WAYPOINTRequest> should match 
// service_traits::DataType< ::g2s_interface::runGOTO_WAYPOINT > 
template<>
struct DataType< ::g2s_interface::runGOTO_WAYPOINTRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runGOTO_WAYPOINT >::value();
  }
  static const char* value(const ::g2s_interface::runGOTO_WAYPOINTRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::runGOTO_WAYPOINTResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::runGOTO_WAYPOINT > 
template<>
struct MD5Sum< ::g2s_interface::runGOTO_WAYPOINTResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runGOTO_WAYPOINT >::value();
  }
  static const char* value(const ::g2s_interface::runGOTO_WAYPOINTResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runGOTO_WAYPOINTResponse> should match 
// service_traits::DataType< ::g2s_interface::runGOTO_WAYPOINT > 
template<>
struct DataType< ::g2s_interface::runGOTO_WAYPOINTResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runGOTO_WAYPOINT >::value();
  }
  static const char* value(const ::g2s_interface::runGOTO_WAYPOINTResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_RUNGOTO_WAYPOINT_H
