// Generated by gencpp from file g2s_interface/runVIDEO_ACQUISITION.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_RUNVIDEO_ACQUISITION_H
#define G2S_INTERFACE_MESSAGE_RUNVIDEO_ACQUISITION_H

#include <ros/service_traits.h>


#include <g2s_interface/runVIDEO_ACQUISITIONRequest.h>
#include <g2s_interface/runVIDEO_ACQUISITIONResponse.h>


namespace g2s_interface
{

struct runVIDEO_ACQUISITION
{

typedef runVIDEO_ACQUISITIONRequest Request;
typedef runVIDEO_ACQUISITIONResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct runVIDEO_ACQUISITION
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::runVIDEO_ACQUISITION > {
  static const char* value()
  {
    return "509e910fe21fa5e13651b58f26fe9297";
  }

  static const char* value(const ::g2s_interface::runVIDEO_ACQUISITION&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::runVIDEO_ACQUISITION > {
  static const char* value()
  {
    return "g2s_interface/runVIDEO_ACQUISITION";
  }

  static const char* value(const ::g2s_interface::runVIDEO_ACQUISITION&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::runVIDEO_ACQUISITIONRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::runVIDEO_ACQUISITION > 
template<>
struct MD5Sum< ::g2s_interface::runVIDEO_ACQUISITIONRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runVIDEO_ACQUISITION >::value();
  }
  static const char* value(const ::g2s_interface::runVIDEO_ACQUISITIONRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runVIDEO_ACQUISITIONRequest> should match 
// service_traits::DataType< ::g2s_interface::runVIDEO_ACQUISITION > 
template<>
struct DataType< ::g2s_interface::runVIDEO_ACQUISITIONRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runVIDEO_ACQUISITION >::value();
  }
  static const char* value(const ::g2s_interface::runVIDEO_ACQUISITIONRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::runVIDEO_ACQUISITIONResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::runVIDEO_ACQUISITION > 
template<>
struct MD5Sum< ::g2s_interface::runVIDEO_ACQUISITIONResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runVIDEO_ACQUISITION >::value();
  }
  static const char* value(const ::g2s_interface::runVIDEO_ACQUISITIONResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runVIDEO_ACQUISITIONResponse> should match 
// service_traits::DataType< ::g2s_interface::runVIDEO_ACQUISITION > 
template<>
struct DataType< ::g2s_interface::runVIDEO_ACQUISITIONResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runVIDEO_ACQUISITION >::value();
  }
  static const char* value(const ::g2s_interface::runVIDEO_ACQUISITIONResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_RUNVIDEO_ACQUISITION_H
