// Generated by gencpp from file g2s_interface/runWAIT.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_RUNWAIT_H
#define G2S_INTERFACE_MESSAGE_RUNWAIT_H

#include <ros/service_traits.h>


#include <g2s_interface/runWAITRequest.h>
#include <g2s_interface/runWAITResponse.h>


namespace g2s_interface
{

struct runWAIT
{

typedef runWAITRequest Request;
typedef runWAITResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct runWAIT
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::runWAIT > {
  static const char* value()
  {
    return "b4faa0b41569ff2b8886cf12ceaccdd6";
  }

  static const char* value(const ::g2s_interface::runWAIT&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::runWAIT > {
  static const char* value()
  {
    return "g2s_interface/runWAIT";
  }

  static const char* value(const ::g2s_interface::runWAIT&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::runWAITRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::runWAIT > 
template<>
struct MD5Sum< ::g2s_interface::runWAITRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runWAIT >::value();
  }
  static const char* value(const ::g2s_interface::runWAITRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runWAITRequest> should match 
// service_traits::DataType< ::g2s_interface::runWAIT > 
template<>
struct DataType< ::g2s_interface::runWAITRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runWAIT >::value();
  }
  static const char* value(const ::g2s_interface::runWAITRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::runWAITResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::runWAIT > 
template<>
struct MD5Sum< ::g2s_interface::runWAITResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runWAIT >::value();
  }
  static const char* value(const ::g2s_interface::runWAITResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runWAITResponse> should match 
// service_traits::DataType< ::g2s_interface::runWAIT > 
template<>
struct DataType< ::g2s_interface::runWAITResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runWAIT >::value();
  }
  static const char* value(const ::g2s_interface::runWAITResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_RUNWAIT_H
