(cl:in-package g2s_interface-msg)
(cl:export '(HEADER-VAL
          HEADER
          ROBOTBATTERYLEVEL-VAL
          ROBOTBATTERYLEVEL
          ROBOTAUTONOMY-VAL
          ROBOTAUTONOMY
          ROBOTINTERNALTEMPERATURE-VAL
          ROBOTINTERNALTEMPERATURE
          ROBOTINTERNALHUMIDITY-VAL
          ROBOTINTERNALHUMIDITY
          ROBOTMODE-VAL
          ROBOTMODE
          ROBOTSUBMODE-VAL
          ROBOTSUBMODE
))