// Generated by gencpp from file g2s_interface/activateWIFI.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_ACTIVATEWIFI_H
#define G2S_INTERFACE_MESSAGE_ACTIVATEWIFI_H

#include <ros/service_traits.h>


#include <g2s_interface/activateWIFIRequest.h>
#include <g2s_interface/activateWIFIResponse.h>


namespace g2s_interface
{

struct activateWIFI
{

typedef activateWIFIRequest Request;
typedef activateWIFIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct activateWIFI
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::activateWIFI > {
  static const char* value()
  {
    return "71a43a7268e3d956360fcea457136a33";
  }

  static const char* value(const ::g2s_interface::activateWIFI&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::activateWIFI > {
  static const char* value()
  {
    return "g2s_interface/activateWIFI";
  }

  static const char* value(const ::g2s_interface::activateWIFI&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::activateWIFIRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::activateWIFI > 
template<>
struct MD5Sum< ::g2s_interface::activateWIFIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::activateWIFI >::value();
  }
  static const char* value(const ::g2s_interface::activateWIFIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::activateWIFIRequest> should match 
// service_traits::DataType< ::g2s_interface::activateWIFI > 
template<>
struct DataType< ::g2s_interface::activateWIFIRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::activateWIFI >::value();
  }
  static const char* value(const ::g2s_interface::activateWIFIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::activateWIFIResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::activateWIFI > 
template<>
struct MD5Sum< ::g2s_interface::activateWIFIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::activateWIFI >::value();
  }
  static const char* value(const ::g2s_interface::activateWIFIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::activateWIFIResponse> should match 
// service_traits::DataType< ::g2s_interface::activateWIFI > 
template<>
struct DataType< ::g2s_interface::activateWIFIResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::activateWIFI >::value();
  }
  static const char* value(const ::g2s_interface::activateWIFIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_ACTIVATEWIFI_H
