// Generated by gencpp from file g2s_interface/activateLIGHT.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_ACTIVATELIGHT_H
#define G2S_INTERFACE_MESSAGE_ACTIVATELIGHT_H

#include <ros/service_traits.h>


#include <g2s_interface/activateLIGHTRequest.h>
#include <g2s_interface/activateLIGHTResponse.h>


namespace g2s_interface
{

struct activateLIGHT
{

typedef activateLIGHTRequest Request;
typedef activateLIGHTResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct activateLIGHT
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::activateLIGHT > {
  static const char* value()
  {
    return "b9a6d0138b9312c3b6c5b8d499b2b490";
  }

  static const char* value(const ::g2s_interface::activateLIGHT&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::activateLIGHT > {
  static const char* value()
  {
    return "g2s_interface/activateLIGHT";
  }

  static const char* value(const ::g2s_interface::activateLIGHT&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::activateLIGHTRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::activateLIGHT > 
template<>
struct MD5Sum< ::g2s_interface::activateLIGHTRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::activateLIGHT >::value();
  }
  static const char* value(const ::g2s_interface::activateLIGHTRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::activateLIGHTRequest> should match 
// service_traits::DataType< ::g2s_interface::activateLIGHT > 
template<>
struct DataType< ::g2s_interface::activateLIGHTRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::activateLIGHT >::value();
  }
  static const char* value(const ::g2s_interface::activateLIGHTRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::activateLIGHTResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::activateLIGHT > 
template<>
struct MD5Sum< ::g2s_interface::activateLIGHTResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::activateLIGHT >::value();
  }
  static const char* value(const ::g2s_interface::activateLIGHTResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::activateLIGHTResponse> should match 
// service_traits::DataType< ::g2s_interface::activateLIGHT > 
template<>
struct DataType< ::g2s_interface::activateLIGHTResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::activateLIGHT >::value();
  }
  static const char* value(const ::g2s_interface::activateLIGHTResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_ACTIVATELIGHT_H
