// Generated by gencpp from file g2s_interface/activateSONAR.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_ACTIVATESONAR_H
#define G2S_INTERFACE_MESSAGE_ACTIVATESONAR_H

#include <ros/service_traits.h>


#include <g2s_interface/activateSONARRequest.h>
#include <g2s_interface/activateSONARResponse.h>


namespace g2s_interface
{

struct activateSONAR
{

typedef activateSONARRequest Request;
typedef activateSONARResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct activateSONAR
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::activateSONAR > {
  static const char* value()
  {
    return "71a43a7268e3d956360fcea457136a33";
  }

  static const char* value(const ::g2s_interface::activateSONAR&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::activateSONAR > {
  static const char* value()
  {
    return "g2s_interface/activateSONAR";
  }

  static const char* value(const ::g2s_interface::activateSONAR&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::activateSONARRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::activateSONAR > 
template<>
struct MD5Sum< ::g2s_interface::activateSONARRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::activateSONAR >::value();
  }
  static const char* value(const ::g2s_interface::activateSONARRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::activateSONARRequest> should match 
// service_traits::DataType< ::g2s_interface::activateSONAR > 
template<>
struct DataType< ::g2s_interface::activateSONARRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::activateSONAR >::value();
  }
  static const char* value(const ::g2s_interface::activateSONARRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::activateSONARResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::activateSONAR > 
template<>
struct MD5Sum< ::g2s_interface::activateSONARResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::activateSONAR >::value();
  }
  static const char* value(const ::g2s_interface::activateSONARResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::activateSONARResponse> should match 
// service_traits::DataType< ::g2s_interface::activateSONAR > 
template<>
struct DataType< ::g2s_interface::activateSONARResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::activateSONAR >::value();
  }
  static const char* value(const ::g2s_interface::activateSONARResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_ACTIVATESONAR_H
