// Generated by gencpp from file g2s_interface/actionStatus.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_ACTIONSTATUS_H
#define G2S_INTERFACE_MESSAGE_ACTIONSTATUS_H

#include <ros/service_traits.h>


#include <g2s_interface/actionStatusRequest.h>
#include <g2s_interface/actionStatusResponse.h>


namespace g2s_interface
{

struct actionStatus
{

typedef actionStatusRequest Request;
typedef actionStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct actionStatus
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::actionStatus > {
  static const char* value()
  {
    return "40e1ff988f8f97dafbffdb638a5673ae";
  }

  static const char* value(const ::g2s_interface::actionStatus&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::actionStatus > {
  static const char* value()
  {
    return "g2s_interface/actionStatus";
  }

  static const char* value(const ::g2s_interface::actionStatus&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::actionStatusRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::actionStatus > 
template<>
struct MD5Sum< ::g2s_interface::actionStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::actionStatus >::value();
  }
  static const char* value(const ::g2s_interface::actionStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::actionStatusRequest> should match 
// service_traits::DataType< ::g2s_interface::actionStatus > 
template<>
struct DataType< ::g2s_interface::actionStatusRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::actionStatus >::value();
  }
  static const char* value(const ::g2s_interface::actionStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::actionStatusResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::actionStatus > 
template<>
struct MD5Sum< ::g2s_interface::actionStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::actionStatus >::value();
  }
  static const char* value(const ::g2s_interface::actionStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::actionStatusResponse> should match 
// service_traits::DataType< ::g2s_interface::actionStatus > 
template<>
struct DataType< ::g2s_interface::actionStatusResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::actionStatus >::value();
  }
  static const char* value(const ::g2s_interface::actionStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_ACTIONSTATUS_H
