// Generated by gencpp from file g2s_interface/powerStatus.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_POWERSTATUS_H
#define G2S_INTERFACE_MESSAGE_POWERSTATUS_H

#include <ros/service_traits.h>


#include <g2s_interface/powerStatusRequest.h>
#include <g2s_interface/powerStatusResponse.h>


namespace g2s_interface
{

struct powerStatus
{

typedef powerStatusRequest Request;
typedef powerStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct powerStatus
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::powerStatus > {
  static const char* value()
  {
    return "a5d64efe8405e2211c86b9923e788d71";
  }

  static const char* value(const ::g2s_interface::powerStatus&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::powerStatus > {
  static const char* value()
  {
    return "g2s_interface/powerStatus";
  }

  static const char* value(const ::g2s_interface::powerStatus&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::powerStatusRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::powerStatus > 
template<>
struct MD5Sum< ::g2s_interface::powerStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::powerStatus >::value();
  }
  static const char* value(const ::g2s_interface::powerStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::powerStatusRequest> should match 
// service_traits::DataType< ::g2s_interface::powerStatus > 
template<>
struct DataType< ::g2s_interface::powerStatusRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::powerStatus >::value();
  }
  static const char* value(const ::g2s_interface::powerStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::powerStatusResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::powerStatus > 
template<>
struct MD5Sum< ::g2s_interface::powerStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::powerStatus >::value();
  }
  static const char* value(const ::g2s_interface::powerStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::powerStatusResponse> should match 
// service_traits::DataType< ::g2s_interface::powerStatus > 
template<>
struct DataType< ::g2s_interface::powerStatusResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::powerStatus >::value();
  }
  static const char* value(const ::g2s_interface::powerStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_POWERSTATUS_H
