// Generated by gencpp from file g2s_interface/resetEqpt.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_RESETEQPT_H
#define G2S_INTERFACE_MESSAGE_RESETEQPT_H

#include <ros/service_traits.h>


#include <g2s_interface/resetEqptRequest.h>
#include <g2s_interface/resetEqptResponse.h>


namespace g2s_interface
{

struct resetEqpt
{

typedef resetEqptRequest Request;
typedef resetEqptResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct resetEqpt
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::resetEqpt > {
  static const char* value()
  {
    return "b5355e42a58b4a0869f6eec588b87b38";
  }

  static const char* value(const ::g2s_interface::resetEqpt&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::resetEqpt > {
  static const char* value()
  {
    return "g2s_interface/resetEqpt";
  }

  static const char* value(const ::g2s_interface::resetEqpt&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::resetEqptRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::resetEqpt > 
template<>
struct MD5Sum< ::g2s_interface::resetEqptRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::resetEqpt >::value();
  }
  static const char* value(const ::g2s_interface::resetEqptRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::resetEqptRequest> should match 
// service_traits::DataType< ::g2s_interface::resetEqpt > 
template<>
struct DataType< ::g2s_interface::resetEqptRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::resetEqpt >::value();
  }
  static const char* value(const ::g2s_interface::resetEqptRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::resetEqptResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::resetEqpt > 
template<>
struct MD5Sum< ::g2s_interface::resetEqptResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::resetEqpt >::value();
  }
  static const char* value(const ::g2s_interface::resetEqptResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::resetEqptResponse> should match 
// service_traits::DataType< ::g2s_interface::resetEqpt > 
template<>
struct DataType< ::g2s_interface::resetEqptResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::resetEqpt >::value();
  }
  static const char* value(const ::g2s_interface::resetEqptResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_RESETEQPT_H
