// Generated by gencpp from file g2s_interface/runFOLLOW_STRUCTURE.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_RUNFOLLOW_STRUCTURE_H
#define G2S_INTERFACE_MESSAGE_RUNFOLLOW_STRUCTURE_H

#include <ros/service_traits.h>


#include <g2s_interface/runFOLLOW_STRUCTURERequest.h>
#include <g2s_interface/runFOLLOW_STRUCTUREResponse.h>


namespace g2s_interface
{

struct runFOLLOW_STRUCTURE
{

typedef runFOLLOW_STRUCTURERequest Request;
typedef runFOLLOW_STRUCTUREResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct runFOLLOW_STRUCTURE
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::runFOLLOW_STRUCTURE > {
  static const char* value()
  {
    return "b4faa0b41569ff2b8886cf12ceaccdd6";
  }

  static const char* value(const ::g2s_interface::runFOLLOW_STRUCTURE&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::runFOLLOW_STRUCTURE > {
  static const char* value()
  {
    return "g2s_interface/runFOLLOW_STRUCTURE";
  }

  static const char* value(const ::g2s_interface::runFOLLOW_STRUCTURE&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::runFOLLOW_STRUCTURERequest> should match 
// service_traits::MD5Sum< ::g2s_interface::runFOLLOW_STRUCTURE > 
template<>
struct MD5Sum< ::g2s_interface::runFOLLOW_STRUCTURERequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runFOLLOW_STRUCTURE >::value();
  }
  static const char* value(const ::g2s_interface::runFOLLOW_STRUCTURERequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runFOLLOW_STRUCTURERequest> should match 
// service_traits::DataType< ::g2s_interface::runFOLLOW_STRUCTURE > 
template<>
struct DataType< ::g2s_interface::runFOLLOW_STRUCTURERequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runFOLLOW_STRUCTURE >::value();
  }
  static const char* value(const ::g2s_interface::runFOLLOW_STRUCTURERequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::runFOLLOW_STRUCTUREResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::runFOLLOW_STRUCTURE > 
template<>
struct MD5Sum< ::g2s_interface::runFOLLOW_STRUCTUREResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runFOLLOW_STRUCTURE >::value();
  }
  static const char* value(const ::g2s_interface::runFOLLOW_STRUCTUREResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runFOLLOW_STRUCTUREResponse> should match 
// service_traits::DataType< ::g2s_interface::runFOLLOW_STRUCTURE > 
template<>
struct DataType< ::g2s_interface::runFOLLOW_STRUCTUREResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runFOLLOW_STRUCTURE >::value();
  }
  static const char* value(const ::g2s_interface::runFOLLOW_STRUCTUREResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_RUNFOLLOW_STRUCTURE_H
