// Generated by gencpp from file g2s_interface/runFOLLOW_ROW.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_RUNFOLLOW_ROW_H
#define G2S_INTERFACE_MESSAGE_RUNFOLLOW_ROW_H

#include <ros/service_traits.h>


#include <g2s_interface/runFOLLOW_ROWRequest.h>
#include <g2s_interface/runFOLLOW_ROWResponse.h>


namespace g2s_interface
{

struct runFOLLOW_ROW
{

typedef runFOLLOW_ROWRequest Request;
typedef runFOLLOW_ROWResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct runFOLLOW_ROW
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::runFOLLOW_ROW > {
  static const char* value()
  {
    return "c1319743356fb6ec0d01da834289fb85";
  }

  static const char* value(const ::g2s_interface::runFOLLOW_ROW&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::runFOLLOW_ROW > {
  static const char* value()
  {
    return "g2s_interface/runFOLLOW_ROW";
  }

  static const char* value(const ::g2s_interface::runFOLLOW_ROW&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::runFOLLOW_ROWRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::runFOLLOW_ROW > 
template<>
struct MD5Sum< ::g2s_interface::runFOLLOW_ROWRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runFOLLOW_ROW >::value();
  }
  static const char* value(const ::g2s_interface::runFOLLOW_ROWRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runFOLLOW_ROWRequest> should match 
// service_traits::DataType< ::g2s_interface::runFOLLOW_ROW > 
template<>
struct DataType< ::g2s_interface::runFOLLOW_ROWRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runFOLLOW_ROW >::value();
  }
  static const char* value(const ::g2s_interface::runFOLLOW_ROWRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::runFOLLOW_ROWResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::runFOLLOW_ROW > 
template<>
struct MD5Sum< ::g2s_interface::runFOLLOW_ROWResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runFOLLOW_ROW >::value();
  }
  static const char* value(const ::g2s_interface::runFOLLOW_ROWResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runFOLLOW_ROWResponse> should match 
// service_traits::DataType< ::g2s_interface::runFOLLOW_ROW > 
template<>
struct DataType< ::g2s_interface::runFOLLOW_ROWResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runFOLLOW_ROW >::value();
  }
  static const char* value(const ::g2s_interface::runFOLLOW_ROWResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_RUNFOLLOW_ROW_H
