// Generated by gencpp from file g2s_interface/runSONAR_SCANNING.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_RUNSONAR_SCANNING_H
#define G2S_INTERFACE_MESSAGE_RUNSONAR_SCANNING_H

#include <ros/service_traits.h>


#include <g2s_interface/runSONAR_SCANNINGRequest.h>
#include <g2s_interface/runSONAR_SCANNINGResponse.h>


namespace g2s_interface
{

struct runSONAR_SCANNING
{

typedef runSONAR_SCANNINGRequest Request;
typedef runSONAR_SCANNINGResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct runSONAR_SCANNING
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::runSONAR_SCANNING > {
  static const char* value()
  {
    return "509e910fe21fa5e13651b58f26fe9297";
  }

  static const char* value(const ::g2s_interface::runSONAR_SCANNING&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::runSONAR_SCANNING > {
  static const char* value()
  {
    return "g2s_interface/runSONAR_SCANNING";
  }

  static const char* value(const ::g2s_interface::runSONAR_SCANNING&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::runSONAR_SCANNINGRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::runSONAR_SCANNING > 
template<>
struct MD5Sum< ::g2s_interface::runSONAR_SCANNINGRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runSONAR_SCANNING >::value();
  }
  static const char* value(const ::g2s_interface::runSONAR_SCANNINGRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runSONAR_SCANNINGRequest> should match 
// service_traits::DataType< ::g2s_interface::runSONAR_SCANNING > 
template<>
struct DataType< ::g2s_interface::runSONAR_SCANNINGRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runSONAR_SCANNING >::value();
  }
  static const char* value(const ::g2s_interface::runSONAR_SCANNINGRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::runSONAR_SCANNINGResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::runSONAR_SCANNING > 
template<>
struct MD5Sum< ::g2s_interface::runSONAR_SCANNINGResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runSONAR_SCANNING >::value();
  }
  static const char* value(const ::g2s_interface::runSONAR_SCANNINGResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runSONAR_SCANNINGResponse> should match 
// service_traits::DataType< ::g2s_interface::runSONAR_SCANNING > 
template<>
struct DataType< ::g2s_interface::runSONAR_SCANNINGResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runSONAR_SCANNING >::value();
  }
  static const char* value(const ::g2s_interface::runSONAR_SCANNINGResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_RUNSONAR_SCANNING_H
