// Generated by gencpp from file g2s_interface/runTRACK_TARGET.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_RUNTRACK_TARGET_H
#define G2S_INTERFACE_MESSAGE_RUNTRACK_TARGET_H

#include <ros/service_traits.h>


#include <g2s_interface/runTRACK_TARGETRequest.h>
#include <g2s_interface/runTRACK_TARGETResponse.h>


namespace g2s_interface
{

struct runTRACK_TARGET
{

typedef runTRACK_TARGETRequest Request;
typedef runTRACK_TARGETResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct runTRACK_TARGET
} // namespace g2s_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::g2s_interface::runTRACK_TARGET > {
  static const char* value()
  {
    return "b4faa0b41569ff2b8886cf12ceaccdd6";
  }

  static const char* value(const ::g2s_interface::runTRACK_TARGET&) { return value(); }
};

template<>
struct DataType< ::g2s_interface::runTRACK_TARGET > {
  static const char* value()
  {
    return "g2s_interface/runTRACK_TARGET";
  }

  static const char* value(const ::g2s_interface::runTRACK_TARGET&) { return value(); }
};


// service_traits::MD5Sum< ::g2s_interface::runTRACK_TARGETRequest> should match 
// service_traits::MD5Sum< ::g2s_interface::runTRACK_TARGET > 
template<>
struct MD5Sum< ::g2s_interface::runTRACK_TARGETRequest>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runTRACK_TARGET >::value();
  }
  static const char* value(const ::g2s_interface::runTRACK_TARGETRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runTRACK_TARGETRequest> should match 
// service_traits::DataType< ::g2s_interface::runTRACK_TARGET > 
template<>
struct DataType< ::g2s_interface::runTRACK_TARGETRequest>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runTRACK_TARGET >::value();
  }
  static const char* value(const ::g2s_interface::runTRACK_TARGETRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::g2s_interface::runTRACK_TARGETResponse> should match 
// service_traits::MD5Sum< ::g2s_interface::runTRACK_TARGET > 
template<>
struct MD5Sum< ::g2s_interface::runTRACK_TARGETResponse>
{
  static const char* value()
  {
    return MD5Sum< ::g2s_interface::runTRACK_TARGET >::value();
  }
  static const char* value(const ::g2s_interface::runTRACK_TARGETResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::g2s_interface::runTRACK_TARGETResponse> should match 
// service_traits::DataType< ::g2s_interface::runTRACK_TARGET > 
template<>
struct DataType< ::g2s_interface::runTRACK_TARGETResponse>
{
  static const char* value()
  {
    return DataType< ::g2s_interface::runTRACK_TARGET >::value();
  }
  static const char* value(const ::g2s_interface::runTRACK_TARGETResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_RUNTRACK_TARGET_H
