// Generated by gencpp from file g2s_interface/waterData.msg
// DO NOT EDIT!


#ifndef G2S_INTERFACE_MESSAGE_WATERDATA_H
#define G2S_INTERFACE_MESSAGE_WATERDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace g2s_interface
{
template <class ContainerAllocator>
struct waterData_
{
  typedef waterData_<ContainerAllocator> Type;

  waterData_()
    : wTemperature(0.0)
    , wSalinity(0.0)
    , wPressure(0.0)
    , wSoundSpeed(0.0)
    , wTurbidity(0.0)
    , wPH(0.0)
    , wLevelH2S(0.0)
    , wLevelDVL(0.0)  {
    }
  waterData_(const ContainerAllocator& _alloc)
    : wTemperature(0.0)
    , wSalinity(0.0)
    , wPressure(0.0)
    , wSoundSpeed(0.0)
    , wTurbidity(0.0)
    , wPH(0.0)
    , wLevelH2S(0.0)
    , wLevelDVL(0.0)  {
    }



   typedef float _wTemperature_type;
  _wTemperature_type wTemperature;

   typedef float _wSalinity_type;
  _wSalinity_type wSalinity;

   typedef float _wPressure_type;
  _wPressure_type wPressure;

   typedef float _wSoundSpeed_type;
  _wSoundSpeed_type wSoundSpeed;

   typedef float _wTurbidity_type;
  _wTurbidity_type wTurbidity;

   typedef float _wPH_type;
  _wPH_type wPH;

   typedef float _wLevelH2S_type;
  _wLevelH2S_type wLevelH2S;

   typedef float _wLevelDVL_type;
  _wLevelDVL_type wLevelDVL;




  typedef boost::shared_ptr< ::g2s_interface::waterData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::g2s_interface::waterData_<ContainerAllocator> const> ConstPtr;

}; // struct waterData_

typedef ::g2s_interface::waterData_<std::allocator<void> > waterData;

typedef boost::shared_ptr< ::g2s_interface::waterData > waterDataPtr;
typedef boost::shared_ptr< ::g2s_interface::waterData const> waterDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::g2s_interface::waterData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::g2s_interface::waterData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace g2s_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'g2s_interface': ['/home/uvlab/swarms/catkin_ws/src/rgi_rsi/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::g2s_interface::waterData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::g2s_interface::waterData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::g2s_interface::waterData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::g2s_interface::waterData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::g2s_interface::waterData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::g2s_interface::waterData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::g2s_interface::waterData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bcbdf64fb0f657368c3dd4ee9609570";
  }

  static const char* value(const ::g2s_interface::waterData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bcbdf64fb0f6573ULL;
  static const uint64_t static_value2 = 0x68c3dd4ee9609570ULL;
};

template<class ContainerAllocator>
struct DataType< ::g2s_interface::waterData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "g2s_interface/waterData";
  }

  static const char* value(const ::g2s_interface::waterData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::g2s_interface::waterData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 wTemperature\n\
float32 wSalinity\n\
float32 wPressure\n\
float32 wSoundSpeed\n\
float32 wTurbidity\n\
float32 wPH\n\
float32 wLevelH2S\n\
float32 wLevelDVL\n\
\n\
\n\
";
  }

  static const char* value(const ::g2s_interface::waterData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::g2s_interface::waterData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wTemperature);
      stream.next(m.wSalinity);
      stream.next(m.wPressure);
      stream.next(m.wSoundSpeed);
      stream.next(m.wTurbidity);
      stream.next(m.wPH);
      stream.next(m.wLevelH2S);
      stream.next(m.wLevelDVL);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct waterData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::g2s_interface::waterData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::g2s_interface::waterData_<ContainerAllocator>& v)
  {
    s << indent << "wTemperature: ";
    Printer<float>::stream(s, indent + "  ", v.wTemperature);
    s << indent << "wSalinity: ";
    Printer<float>::stream(s, indent + "  ", v.wSalinity);
    s << indent << "wPressure: ";
    Printer<float>::stream(s, indent + "  ", v.wPressure);
    s << indent << "wSoundSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.wSoundSpeed);
    s << indent << "wTurbidity: ";
    Printer<float>::stream(s, indent + "  ", v.wTurbidity);
    s << indent << "wPH: ";
    Printer<float>::stream(s, indent + "  ", v.wPH);
    s << indent << "wLevelH2S: ";
    Printer<float>::stream(s, indent + "  ", v.wLevelH2S);
    s << indent << "wLevelDVL: ";
    Printer<float>::stream(s, indent + "  ", v.wLevelDVL);
  }
};

} // namespace message_operations
} // namespace ros

#endif // G2S_INTERFACE_MESSAGE_WATERDATA_H
