// Generated by gencpp from file rsi_lauv_ntnu/testSrvRsiLauv.msg
// DO NOT EDIT!


#ifndef RSI_LAUV_NTNU_MESSAGE_TESTSRVRSILAUV_H
#define RSI_LAUV_NTNU_MESSAGE_TESTSRVRSILAUV_H

#include <ros/service_traits.h>


#include <rsi_lauv_ntnu/testSrvRsiLauvRequest.h>
#include <rsi_lauv_ntnu/testSrvRsiLauvResponse.h>


namespace rsi_lauv_ntnu
{

struct testSrvRsiLauv
{

typedef testSrvRsiLauvRequest Request;
typedef testSrvRsiLauvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct testSrvRsiLauv
} // namespace rsi_lauv_ntnu


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsi_lauv_ntnu::testSrvRsiLauv > {
  static const char* value()
  {
    return "b1a7f91fd2b1c43250210e7f7aab9928";
  }

  static const char* value(const ::rsi_lauv_ntnu::testSrvRsiLauv&) { return value(); }
};

template<>
struct DataType< ::rsi_lauv_ntnu::testSrvRsiLauv > {
  static const char* value()
  {
    return "rsi_lauv_ntnu/testSrvRsiLauv";
  }

  static const char* value(const ::rsi_lauv_ntnu::testSrvRsiLauv&) { return value(); }
};


// service_traits::MD5Sum< ::rsi_lauv_ntnu::testSrvRsiLauvRequest> should match 
// service_traits::MD5Sum< ::rsi_lauv_ntnu::testSrvRsiLauv > 
template<>
struct MD5Sum< ::rsi_lauv_ntnu::testSrvRsiLauvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsi_lauv_ntnu::testSrvRsiLauv >::value();
  }
  static const char* value(const ::rsi_lauv_ntnu::testSrvRsiLauvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsi_lauv_ntnu::testSrvRsiLauvRequest> should match 
// service_traits::DataType< ::rsi_lauv_ntnu::testSrvRsiLauv > 
template<>
struct DataType< ::rsi_lauv_ntnu::testSrvRsiLauvRequest>
{
  static const char* value()
  {
    return DataType< ::rsi_lauv_ntnu::testSrvRsiLauv >::value();
  }
  static const char* value(const ::rsi_lauv_ntnu::testSrvRsiLauvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsi_lauv_ntnu::testSrvRsiLauvResponse> should match 
// service_traits::MD5Sum< ::rsi_lauv_ntnu::testSrvRsiLauv > 
template<>
struct MD5Sum< ::rsi_lauv_ntnu::testSrvRsiLauvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsi_lauv_ntnu::testSrvRsiLauv >::value();
  }
  static const char* value(const ::rsi_lauv_ntnu::testSrvRsiLauvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsi_lauv_ntnu::testSrvRsiLauvResponse> should match 
// service_traits::DataType< ::rsi_lauv_ntnu::testSrvRsiLauv > 
template<>
struct DataType< ::rsi_lauv_ntnu::testSrvRsiLauvResponse>
{
  static const char* value()
  {
    return DataType< ::rsi_lauv_ntnu::testSrvRsiLauv >::value();
  }
  static const char* value(const ::rsi_lauv_ntnu::testSrvRsiLauvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSI_LAUV_NTNU_MESSAGE_TESTSRVRSILAUV_H
