// Generated by gencpp from file rsi_lauv_ntnu/testStationKeeping.msg
// DO NOT EDIT!


#ifndef RSI_LAUV_NTNU_MESSAGE_TESTSTATIONKEEPING_H
#define RSI_LAUV_NTNU_MESSAGE_TESTSTATIONKEEPING_H

#include <ros/service_traits.h>


#include <rsi_lauv_ntnu/testStationKeepingRequest.h>
#include <rsi_lauv_ntnu/testStationKeepingResponse.h>


namespace rsi_lauv_ntnu
{

struct testStationKeeping
{

typedef testStationKeepingRequest Request;
typedef testStationKeepingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct testStationKeeping
} // namespace rsi_lauv_ntnu


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsi_lauv_ntnu::testStationKeeping > {
  static const char* value()
  {
    return "1ed82e7ea96c183f108ce41c99ccd410";
  }

  static const char* value(const ::rsi_lauv_ntnu::testStationKeeping&) { return value(); }
};

template<>
struct DataType< ::rsi_lauv_ntnu::testStationKeeping > {
  static const char* value()
  {
    return "rsi_lauv_ntnu/testStationKeeping";
  }

  static const char* value(const ::rsi_lauv_ntnu::testStationKeeping&) { return value(); }
};


// service_traits::MD5Sum< ::rsi_lauv_ntnu::testStationKeepingRequest> should match 
// service_traits::MD5Sum< ::rsi_lauv_ntnu::testStationKeeping > 
template<>
struct MD5Sum< ::rsi_lauv_ntnu::testStationKeepingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsi_lauv_ntnu::testStationKeeping >::value();
  }
  static const char* value(const ::rsi_lauv_ntnu::testStationKeepingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsi_lauv_ntnu::testStationKeepingRequest> should match 
// service_traits::DataType< ::rsi_lauv_ntnu::testStationKeeping > 
template<>
struct DataType< ::rsi_lauv_ntnu::testStationKeepingRequest>
{
  static const char* value()
  {
    return DataType< ::rsi_lauv_ntnu::testStationKeeping >::value();
  }
  static const char* value(const ::rsi_lauv_ntnu::testStationKeepingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsi_lauv_ntnu::testStationKeepingResponse> should match 
// service_traits::MD5Sum< ::rsi_lauv_ntnu::testStationKeeping > 
template<>
struct MD5Sum< ::rsi_lauv_ntnu::testStationKeepingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsi_lauv_ntnu::testStationKeeping >::value();
  }
  static const char* value(const ::rsi_lauv_ntnu::testStationKeepingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsi_lauv_ntnu::testStationKeepingResponse> should match 
// service_traits::DataType< ::rsi_lauv_ntnu::testStationKeeping > 
template<>
struct DataType< ::rsi_lauv_ntnu::testStationKeepingResponse>
{
  static const char* value()
  {
    return DataType< ::rsi_lauv_ntnu::testStationKeeping >::value();
  }
  static const char* value(const ::rsi_lauv_ntnu::testStationKeepingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSI_LAUV_NTNU_MESSAGE_TESTSTATIONKEEPING_H
