# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from g2s_interface/waterData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class waterData(genpy.Message):
  _md5sum = "9bcbdf64fb0f657368c3dd4ee9609570"
  _type = "g2s_interface/waterData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 wTemperature
float32 wSalinity
float32 wPressure
float32 wSoundSpeed
float32 wTurbidity
float32 wPH
float32 wLevelH2S
float32 wLevelDVL



"""
  __slots__ = ['wTemperature','wSalinity','wPressure','wSoundSpeed','wTurbidity','wPH','wLevelH2S','wLevelDVL']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       wTemperature,wSalinity,wPressure,wSoundSpeed,wTurbidity,wPH,wLevelH2S,wLevelDVL

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(waterData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.wTemperature is None:
        self.wTemperature = 0.
      if self.wSalinity is None:
        self.wSalinity = 0.
      if self.wPressure is None:
        self.wPressure = 0.
      if self.wSoundSpeed is None:
        self.wSoundSpeed = 0.
      if self.wTurbidity is None:
        self.wTurbidity = 0.
      if self.wPH is None:
        self.wPH = 0.
      if self.wLevelH2S is None:
        self.wLevelH2S = 0.
      if self.wLevelDVL is None:
        self.wLevelDVL = 0.
    else:
      self.wTemperature = 0.
      self.wSalinity = 0.
      self.wPressure = 0.
      self.wSoundSpeed = 0.
      self.wTurbidity = 0.
      self.wPH = 0.
      self.wLevelH2S = 0.
      self.wLevelDVL = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_8f.pack(_x.wTemperature, _x.wSalinity, _x.wPressure, _x.wSoundSpeed, _x.wTurbidity, _x.wPH, _x.wLevelH2S, _x.wLevelDVL))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.wTemperature, _x.wSalinity, _x.wPressure, _x.wSoundSpeed, _x.wTurbidity, _x.wPH, _x.wLevelH2S, _x.wLevelDVL,) = _struct_8f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_8f.pack(_x.wTemperature, _x.wSalinity, _x.wPressure, _x.wSoundSpeed, _x.wTurbidity, _x.wPH, _x.wLevelH2S, _x.wLevelDVL))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.wTemperature, _x.wSalinity, _x.wPressure, _x.wSoundSpeed, _x.wTurbidity, _x.wPH, _x.wLevelH2S, _x.wLevelDVL,) = _struct_8f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_8f = struct.Struct("<8f")
